### ISSUE TITLE
你好，伴随着数据源配置，通常还会有事务的配置，事务大都用XML吧，这种的话事务能不能配置？

### ISSUE THREAD

**Issue by ExtremeYu** [drtrang/druid-spring-boot#1]

**Comment by drtrang** [comment]
首先Spring 官方是不推荐 SpringBoot 搭配 XML 使用的，与 Spring 相关的一切配置均可以用 JavaConfig 方式代替。
如果你使用了 SpringBoot 的话，SpringBoot 会自动注入默认的事务管理器，源码在
 `org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration`。引入了 Druid Spring Boot Starter 后并没有什么不同，只是不需要在代码里去手动声明 DataSource。
