### ISSUE TITLE
多数据源那块有具体示例吗？在代码中如何显示指定哪些操作有哪个数据源?

### ISSUE THREAD

**Issue by michael-ancestor** [drtrang/druid-spring-boot#11]
hi,多数据源那块有具体示例吗？在代码中如何显示指定哪些操作有哪个数据源?(比如selectA走mysql数据源;selectB走阿里ADS数据源)

另外，【dynamic-data-source-demo】中演示的动态数据源和【druid-spring-boot】中的多数据源有什么区别吗?

**Comment by drtrang** [comment]
@michael-ancestor dynamic-data-source-demo 中使用的是老版本的 druid spring boot starter，最新版的实例可以从 [druid-spring-boot-mybatis-example](https://github.com/drtrang/druid-spring-boot/tree/master/druid-spring-boot-example/druid-spring-boot-mybatis-example) 中找到。

对于第一个问题，starter 会自动注册多个 DataSource，但是如何使用多个数据源即具体的路由规则需要用户自己实现，比如 example 中基于 AbstractRoutingDataSource 实现了简单的轮询方式路由。

**Comment by drtrang** [comment]
@michael-ancestor 不知上述回答是否解决了你的疑问？该 ISSUE 我先关闭了，如需帮助请重新打开。
