### ISSUE TITLE
确定能用？

### ISSUE THREAD

**Issue by zhangjw-ECHO** [drtrang/druid-spring-boot#14]
确定能用？

**Comment by drtrang** [comment]
请问有什么问题吗？example 里有测试用例和演示，是可以运行的。

**Comment by drtrang** [comment]
@zhangjw-ECHO 谨慎起见，我把本地的 jar 包全部删除，从中央仓库重新下载 jar 包后又测试了一遍是没有问题的，`druid-spring-boot-starter` 和 `druid-spring-boot2-starter` 均可以通过单元测试，因暂不明确该
 ISSUE 所描述的问题场景，所以我先关闭了。如你那边仍有问题，请详细描述下问题，方便我排查，谢谢。

**Comment by zhangjw-ECHO** [comment]
RelaxedPropertyResolver 被删除的原因
