### ISSUE TITLE
1.1.9 版本缺少parent 依赖，所以starter依赖无法正常使用

### ISSUE THREAD

**Issue by gumutianqi** [drtrang/druid-spring-boot#16]
@drtrang 

如下图，因为后面的module版本号都在parent里面，而1.1.9的parent包没有上传到maven中央仓库，所以后面的依赖都无法正常使用：

主要是spring boot 1.x的那个parent依赖没有

![2018-04-24 17 11 00](https://user-images.githubusercontent.com/1057589/39177691-83218cba-47e2-11e8-93f0-98b8c2028a92.png)

这么明显不能用的问题，难道就没人发现么

**Comment by drtrang** [comment]
@gumutianqi

Sorry，该问题是已知问题，在上传到中央仓库的过程中，由于网络的问题导致 `druid-spring-boot-parent` 没有上传成功，所以 1.1.9 版本不能使用，目前请先使用 1.1.8 版本。

5.1 期间我会发布一个 fix 版本，届时可以更新到最新版。

给你带来的不便请见谅。

**Comment by drtrang** [comment]
@gumutianqi 

1.1.9.1 修复版本以提前发布，请更新。

```xml
<!-- spring boot 1.x -->
<dependency>
    <groupId>com.github.drtrang</groupId>
    <artifactId>druid-spring-boot-starter</artifactId>
    <version>1.1.9.1</version>
</dependency>

<!-- spring boot 2.x -->
<dependency>
    <groupId>com.github.drtrang</groupId>
    <artifactId>druid-spring-boot2-starter</artifactId>
    <version>1.1.9</version>
</dependency>
```
