### ISSUE TITLE
再引用的时候出现这个问题

### ISSUE THREAD

**Issue by af826** [drtrang/druid-spring-boot#5]
org.springframework.beans.factory.BeanDefinitionStoreException: Failed to process import candidates for configuration class [com.github.trang.druid.DruidAutoConfiguration]; nested exception is java.lang.ClassCastException: java.lang.UnsupportedClassVersionError cannot be cast to [Ljava.lang.Object;
_我采用的是_properties配置方式
Boot版本1.5.4.RELEASE

**Comment by drtrang** [comment]
机器上装的 JDK 版本是多少？用的是 SpringBoot 的内嵌容器？

**Comment by ipqihujf** [comment]
org.springframework.beans.factory.BeanDefinitionStoreException: Failed to process import candidates for configuration class [com.github.trang.druid.DruidStatConfiguration]; nested exception is java.lang.ClassCastException: java.lang.UnsupportedClassVersionError cannot be cast to [Ljava.lang.Object;
	at org.springframework.context.annotation.ConfigurationClassParser.processImports(ConfigurationClassParser.java:616) ~[spring-context-4.3.10.RELEASE.jar:4.3.10.RELEASE]

**Comment by drtrang** [comment]
@af826 @ipqihujf 能把 `Application` 的代码和 `pom.xml` 文件的内容贴上来吗？目前信息量太少定位困难，可以看看 `@SpringBootApplication` 注解和 `spring-boot-maven-plugin` 是否配置正确。

**Comment by af826** [comment]
抱歉很久没上，回复你，已经换了实现方式
