### ISSUE TITLE
能否提供一个基于spring-data-jpa的配置

### ISSUE THREAD

**Issue by althyman** [drtrang/druid-spring-boot#6]
目前示例是根据mybatis来配置的，由于jpa与mybatis在引用数据源及事务方面存在差异，是否能提供一个基于jpa的配置。
谢谢~

**Comment by drtrang** [comment]
抽空会写一个，不过 Druid 只是一个数据库连接池，应该不会影响 JPA 的配置。

**Comment by drtrang** [comment]
@althyman Sorry，今年事情较多，目前已增加基于 JPA 的代码实例 [druid-spring-boot-jpa-example](https://github.com/drtrang/druid-spring-boot/tree/master/druid-spring-boot-example/druid-spring-boot-jpa-example)
