### ISSUE TITLE
exclusions设置无效

### ISSUE THREAD

**Issue by 18506711722** [drtrang/druid-spring-boot#7]
web-stat:
          enabled: true
          url-patterns: /*
          # 该属性设置好像无效
          exclusions: 99.js

**Comment by drtrang** [comment]
我这测试是可以的，以下是我的测试场景：
## 默认
```yml
web-stat:
  enabled: true
````

开启 WebStatFilter 后默认会过滤 `*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*`，代码在这里：![DruidDataSourceProperties](https://github.com/drtrang/druid-spring-boot/blob/master/druid-spring-boot-autoconfigure/src/main/java/com/github/trang/druid/autoconfigure/properties/DruidDataSourceProperties.java#L81)

从 WebStatFilter 的注入情况来看符合默认配置

![image](https://user-images.githubusercontent.com/13851701/31601237-d2925f1e-b28b-11e7-9e92-a3510c834fa8.png)

从 Druid 的监控上来看也是没有问题的，`/druid/*` 相关的 URL 均被屏蔽，`/city/*` 可以展示

![image](https://user-images.githubusercontent.com/13851701/31601346-2981a578-b28c-11e7-9faa-d1a238b3da97.png)

## 自定义
```yml
web-stat:
  enabled: true
  exclusions: /city/*
````

从 WebStatFilter 的注入情况来看符合自定义配置


从 Druid 的监控上来看，`/city/*` 相关的 URL 被屏蔽，其它请求可以展示

**Comment by drtrang** [comment]
@18506711722 你好，该 ISSUE 我先行关闭，如仍有问题请重新打开并描述问题，谢谢。
