### ISSUE TITLE
这个不是有官方的 starter 么？

### ISSUE THREAD

**Issue by gumutianqi** [drtrang/druid-spring-boot#8]
这个和Druid 官方的 springboot-starter 有什么区别，我看配置项都一样

```
https://github.com/alibaba/druid/tree/master/druid-spring-boot-starter
```

**Comment by drtrang** [comment]
做的时候官方还没有，实现方式官方参考了我的方案，二者没有本质区别，如果说优点的话我做的会更友好一些并且会不断优化。

**Comment by drtrang** [comment]
@gumutianqi 基于 spring-boot 2.x 版本的 starter 已发布，欢迎使用。该问题没有需要解决的问题，我先关闭了。

**Comment by it-noob** [comment]
有考虑给官方提交pr，共同维护么？感觉非官方的话，可能会随时停止维护
